#!/usr/bin/env bash

set -e

echo "Installing Brew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Restoring configuration files..."
./restore_configuration_files

echo "Installing packages..."
brew bundle
